In [11]:
import numpy as np


In [10]:
pip install numpy

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the 'C:\Users\santi\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [20]:
#Create a 1D array of numbers from 0 to 9

array = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(array[0:10])

[0 1 2 3 4 5 6 7 8 9]


In [26]:
#Create a 3×3 NumPy array of all Boolean value Trues
variable_name = np.zeros([3,3])
print('3D Numpy Array: ')
print(variable_name)


3D Numpy Array: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
#Extract all odd numbers from array of 1-10

a = np.array([1,2,3,4,5,6,7,8,9,10])
print (a[0:10:2])


[1 3 5 7 9]


In [36]:
#Replace all odd numbers in an array of 1-10 with the value -1
 
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) 
print (a[0:10:2]-1)

[0 2 4 6 8]


In [50]:
#Convert a 1D array to a 2D array with 2 rows

b = np.array([1,2,3,4]) 
c = b.reshape(2,2)

print(c)

[[1 2]
 [3 4]]


In [58]:
#Create two arrays a and b, stack these two arrays vertically use the np.dot and 
#np.sum to calculate totals

a = np.array([1, 2, 3, 4])
b = np.array([4, 5, 6, 7])
c = np.vstack((a, b))
print (c)
d = np.dot (a,b)
print (d)
e = np.sum (c)
print (e)
             

[[1 2 3 4]
 [4 5 6 7]]
60
32
